### ISSUE TITLE
大佬嘤嘤嘤，想问有什么办法python实现远程监督的pubmed artical和UMLS关系组的对齐啊

### ISSUE THREAD

**Issue by soulofshadow** [DevilExileSu/UMLS-MetaMap-Aligned#1]
如果不用这个MetaMap， 能通过bert这种模型来extract吗？

**Comment by DevilExileSu** [comment]
如果只是用来抽取 pubmed artical 中的一些实体和关系，可以使用 biobert 来完成，但是实体类别和关系类别没有那么多。据我了解，目前的公开的医学数据集没有那么多的实体和关系，所以才会考虑借助UMLS，通过远程监督在没有训练集或者训练集很少的情况下，来训练模型，实现抽取一些现有数据集中不存在的实体和关系，但是为了从远程知识库UMLS来实现数据集的标注，就需要借助MetaMap，先通过MetaMap抽取数据集中每个句子中的实体，获取实体对应的CUI，在再MRREL.RRF中进行对齐，这里的对齐就是判断句子中的两个实体CUI，是否可以匹配上MRREL.RRF中某个关系中的两个实体CUI，如果有我们就假设该句子中的这两个实体存在这种关系，那么我们就获得了一条标注过的数据，这也是远程监督的一个核心思想。
我的另一个项目 https://github.com/DevilExileSu/Medical_KGBuild 就是借助 biobert + MetaMap + UMLS + 远程监督实现的一个医学知识图谱构建项目，用来抽取一篇医学文献中基因和癌症之间的信息，并保存到图数据库中。

**Comment by soulofshadow** [comment]
大佬！谢谢回复。我在做我的毕业项目跟这个有关，想多请教一下。

我想做的就是对齐的数据来提取subgraph生成语料库。但是如果不用MetaMap，我看了一下MRCONSO这个文件里面关于实体的描写，就是很多描写就是一句话，而且一个cui对应多个不同的string

<img width="442" alt="image" src="https://user-images.githubusercontent.com/95683271/222903534-3e270c2d-3cb7-4c23-96c6-2050f99fa021.png">

如果是用MetaMap，是用cui来对齐还好，但是如果用bert语言模型，因为如果从文本那一边出发，经过一些NER实体识别，一般是 一些比如，“liver”， “infection” 这种名词一个一个的，我不知道如何来把这些文本中的实体和umls的实体对齐，是要对umls的实体先处理一下吗？但是我总觉得对外部的知识库处理好像不太好的样子。

🙏

**Comment by soulofshadow** [comment]
> 如果只是用来抽取 pubmed artical 中的一些实体和关系，可以使用 biobert 来完成，但是实体类别和关系类别没有那么多。据我了解，目前的公开的医学数据集没有那么多的实体和关系，所以才会考虑借助UMLS，通过**远程监督在没有训练集或者训练集很少的情况下，来训练模型**，实现抽取一些现有数据集中不存在的实体和关系，但是**为了从远程知识库UMLS来实现数据集的标注，就需要借助MetaMap，先通过MetaMap抽取数据集中每个句子中的实体，获取实体对应的CUI**，在再MRREL.RRF中进行对齐，这里的对齐就是判断句子中的两个实体CUI，是否可以匹配上MRREL.RRF中某个关系中的两个实体CUI，如果有我们就假设该句子中的这两个实体存在这种关系，那么我们就获得了一条标注过的数据，这也是远程监督的一个核心思想。


我现在就是没有对齐的数据集，如果我想用UMLS的关系组来对文本进行标注，还是得用 metamap吗？

**Comment by DevilExileSu** [comment]
> 大佬！谢谢回复。我在做我的毕业项目跟这个有关，想多请教一下。
> 
> 我想做的就是对齐的数据来提取subgraph生成语料库。但是如果不用MetaMap，我看了一下MRCONSO这个文件里面关于实体的描写，就是很多描写就是一句话，而且一个cui对应多个不同的string
> 
> <img alt="image" width="442" src="https://user-images.githubusercontent.com/95683271/222903534-3e270c2d-3cb7-4c23-96c6-2050f99fa021.png">
> 
> 如果是用MetaMap，是用cui来对齐还好，但是如果用bert语言模型，因为如果从文本那一边出发，经过一些NER实体识别，一般是 一些比如，“liver”， “infection” 这种名词一个一个的，我不知道如何来把这些文本中的实体和umls的实体对齐，是要对umls的实体先处理一下吗？但是我总觉得对外部的知识库处理好像不太好的样子。
> 
> 🙏

1. 对齐，借助UMLS的关系组对文本进行标注，确实是需要用到 MetaMap，用cui比较好，一个cui对应多个不同string，都属于是同一个实体的不同实体别名。
2. 不需要对umls的实体进行处理，只是借助 umls，以远程监督的方法创建一个标注过的数据集，这个前面也说了，借助MetaMap把未标注的医学句子中，把实体以cui的方法抽取出来，然后 umls 中存在一个关系数据集，包含了一些关系三元组，这些三元组中的实体是以cui的方式记录的，也就是说要想通过 umls 进行远程监督，必须要借助MetaMap，将句子中的实体抽取出来并转换为 cui，之后再去 umls 的关系三元组中找到能够匹配 三元组的句子，将句子打上对应关系的标签。

这也是 **远程监督** 的核心假设：**两个实体如果在知识库中存在某种关系，则包含该两个实体的非结构化句子均能表示出这种关系。**

但实际上，打了标签并不一定真的就代表 这个句子能够表征这两个实体存在这种关系，这个时候就要去使用 **多实例学习(Multi-Instance Learning)** 来减少错误标注所带来的影响，更详细的可以去找找相关的论文看看。

**Comment by soulofshadow** [comment]
大佬大佬，但是这个远程监督我之前就手写了一个，因为他又不涉及模型建立，但是用字符串去匹配寻找三元组就很慢。。

然后对于cui 我能不能训练一个BERT， 把这些所有「string」 和 cui对应的「semantic name」，这个 在mrsty.rff文件里，我把他们当成input和targetfine tune bert，然后再把bert链接CRF做实体抽取

**Comment by DevilExileSu** [comment]
> 大佬大佬，但是这个远程监督我之前就手写了一个，因为他又不涉及模型建立，但是用字符串去匹配寻找三元组就很慢。。
> 
> 然后对于cui 我能不能训练一个BERT， 把这些所有「string」 和 cui对应的「semantic name」，这个 在mrsty.rff文件里，我把他们当成input和targetfine tune bert，然后再把bert链接CRF做实体抽取

😂确实很慢。应该是可以的，但是后面的关系抽取要怎么做？

**Comment by soulofshadow** [comment]
大佬，我放弃挣扎了，MetaMap真的好香。我试了几个UMLSbert_ner， 但是提取的实体不是很好。

现在用MetaMap主要问题就是他是用最长字符串匹配去做实体抽取，所以比较慢，但是同等速度找不到比他效果好的，速度快的效果又很差。

然后远程监督对齐umls的triplets，
<img width="838" alt="image" src="https://user-images.githubusercontent.com/95683271/223179691-29802a54-0cb2-446d-baa3-db61cc13f5a3.png">
我把string cui的c去掉，换成int，数值匹配快多了！

**Comment by DevilExileSu** [comment]
我关闭了这个 issue，如果想要继续讨论，可以添加我的QQ: 912828997
